**

!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml

!apps
apps/*
!apps/web
apps/web/*
!apps/web/package.json
!apps/web/next-env.d.ts
!apps/web/next.config.ts
!apps/web/postcss.config.mjs
!apps/web/redocly.yaml
!apps/web/tsconfig.json
!apps/web/vitest.config.mts
!apps/web/messages
!apps/web/messages/**
!apps/web/public
!apps/web/public/**
!apps/web/src
!apps/web/src/**

!contracts
contracts/*
!contracts/openapi
contracts/openapi/*
!contracts/openapi/v1.json
